//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: update_protocol.proto
namespace update_protocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Position")]
  public partial class Position : global::ProtoBuf.IExtensible
  {
    public Position() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Rotation")]
  public partial class Rotation : global::ProtoBuf.IExtensible
  {
    public Rotation() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _w;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"w", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float w
    {
      get { return _w; }
      set { _w = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DataDescription")]
  public partial class DataDescription : global::ProtoBuf.IExtensible
  {
    public DataDescription() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _dd_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"dd_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dd_id
    {
      get { return _dd_id; }
      set { _dd_id = value; }
    }
    private int _item_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private int _parentId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"parentId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int parentId
    {
      get { return _parentId; }
      set { _parentId = value; }
    }
    private int _parentOffsetX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"parentOffsetX", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int parentOffsetX
    {
      get { return _parentOffsetX; }
      set { _parentOffsetX = value; }
    }
    private int _parentOffsetY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"parentOffsetY", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int parentOffsetY
    {
      get { return _parentOffsetY; }
      set { _parentOffsetY = value; }
    }
    private int _parentOffsetZ;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"parentOffsetZ", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int parentOffsetZ
    {
      get { return _parentOffsetZ; }
      set { _parentOffsetZ = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LabeledMarker")]
  public partial class LabeledMarker : global::ProtoBuf.IExtensible
  {
    public LabeledMarker() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private float _size;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float size
    {
      get { return _size; }
      set { _size = value; }
    }
    private Position _position;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Position position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrackedBody")]
  public partial class TrackedBody : global::ProtoBuf.IExtensible
  {
    public TrackedBody() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _label;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string label
    {
      get { return _label; }
      set { _label = value; }
    }
    private bool _trackingValid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"trackingValid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool trackingValid
    {
      get { return _trackingValid; }
      set { _trackingValid = value; }
    }
    private Position _position;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Position position
    {
      get { return _position; }
      set { _position = value; }
    }
    private Rotation _rotation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public Rotation rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private float _meanError = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"meanError", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float meanError
    {
      get { return _meanError; }
      set { _meanError = value; }
    }
    private readonly global::System.Collections.Generic.List<LabeledMarker> _markers = new global::System.Collections.Generic.List<LabeledMarker>();
    [global::ProtoBuf.ProtoMember(7, Name=@"markers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<LabeledMarker> markers
    {
      get { return _markers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mocap")]
  public partial class Mocap : global::ProtoBuf.IExtensible
  {
    public Mocap() {}
    
    private bool _duringRecording;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"duringRecording", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool duringRecording
    {
      get { return _duringRecording; }
      set { _duringRecording = value; }
    }
    private bool _trackedModelsChanged;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"trackedModelsChanged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool trackedModelsChanged
    {
      get { return _trackedModelsChanged; }
      set { _trackedModelsChanged = value; }
    }
    private string _timecode = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"timecode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string timecode
    {
      get { return _timecode; }
      set { _timecode = value; }
    }
    private readonly global::System.Collections.Generic.List<TrackedBody> _tracked_bodies = new global::System.Collections.Generic.List<TrackedBody>();
    [global::ProtoBuf.ProtoMember(4, Name=@"tracked_bodies", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<TrackedBody> tracked_bodies
    {
      get { return _tracked_bodies; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mote")]
  public partial class Mote : global::ProtoBuf.IExtensible
  {
    public Mote() {}
    
    private string _label;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string label
    {
      get { return _label; }
      set { _label = value; }
    }
    private int _button_bits;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"button_bits", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int button_bits
    {
      get { return _button_bits; }
      set { _button_bits = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Update")]
  public partial class Update : global::ProtoBuf.IExtensible
  {
    public Update() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _mod_version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mod_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mod_version
    {
      get { return _mod_version; }
      set { _mod_version = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private Mocap _mocap = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"mocap", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Mocap mocap
    {
      get { return _mocap; }
      set { _mocap = value; }
    }
    private readonly global::System.Collections.Generic.List<Mote> _motes = new global::System.Collections.Generic.List<Mote>();
    [global::ProtoBuf.ProtoMember(5, Name=@"motes", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Mote> motes
    {
      get { return _motes; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Updates")]
  public partial class Updates : global::ProtoBuf.IExtensible
  {
    public Updates() {}
    
    private int _mod_version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mod_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mod_version
    {
      get { return _mod_version; }
      set { _mod_version = value; }
    }
    private readonly global::System.Collections.Generic.List<Update> _updates = new global::System.Collections.Generic.List<Update>();
    [global::ProtoBuf.ProtoMember(2, Name=@"updates", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Update> updates
    {
      get { return _updates; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}