//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: update_protocol_v3.proto
namespace update_protocol_v3
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ExtraData")]
  public partial class ExtraData : global::ProtoBuf.IExtensible
  {
    public ExtraData() {}
    
    private string _label = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string label
    {
      get { return _label; }
      set { _label = value; }
    }
    private int _int_val = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"int_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int int_val
    {
      get { return _int_val; }
      set { _int_val = value; }
    }
    private float _float_val = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"float_val", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float float_val
    {
      get { return _float_val; }
      set { _float_val = value; }
    }
    private double _double_val = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"double_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double double_val
    {
      get { return _double_val; }
      set { _double_val = value; }
    }
    private string _string_val = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"string_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string string_val
    {
      get { return _string_val; }
      set { _string_val = value; }
    }
    private bool _bool_val = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"bool_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool bool_val
    {
      get { return _bool_val; }
      set { _bool_val = value; }
    }
    private byte[] _bytes_val = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bytes_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] bytes_val
    {
      get { return _bytes_val; }
      set { _bytes_val = value; }
    }
    private readonly global::System.Collections.Generic.List<update_protocol_v3.ExtraData> _extra_val = new global::System.Collections.Generic.List<update_protocol_v3.ExtraData>();
    [global::ProtoBuf.ProtoMember(8, Name=@"extra_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<update_protocol_v3.ExtraData> extra_val
    {
      get { return _extra_val; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AxisButton")]
  public partial class AxisButton : global::ProtoBuf.IExtensible
  {
    public AxisButton() {}
    
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LiveObject")]
  public partial class LiveObject : global::ProtoBuf.IExtensible
  {
    public LiveObject() {}
    
    private string _label = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string label
    {
      get { return _label; }
      set { _label = value; }
    }
    private float _x = default(float);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y = default(float);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private float _qx = default(float);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"qx", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float qx
    {
      get { return _qx; }
      set { _qx = value; }
    }
    private float _qy = default(float);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"qy", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float qy
    {
      get { return _qy; }
      set { _qy = value; }
    }
    private float _qz = default(float);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"qz", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float qz
    {
      get { return _qz; }
      set { _qz = value; }
    }
    private float _qw = default(float);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"qw", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float qw
    {
      get { return _qw; }
      set { _qw = value; }
    }
    private int _button_bits = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"button_bits", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int button_bits
    {
      get { return _button_bits; }
      set { _button_bits = value; }
    }
    private readonly global::System.Collections.Generic.List<update_protocol_v3.AxisButton> _axis_buttons = new global::System.Collections.Generic.List<update_protocol_v3.AxisButton>();
    [global::ProtoBuf.ProtoMember(10, Name=@"axis_buttons", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<update_protocol_v3.AxisButton> axis_buttons
    {
      get { return _axis_buttons; }
    }
  
    private readonly global::System.Collections.Generic.List<update_protocol_v3.ExtraData> _extra_data = new global::System.Collections.Generic.List<update_protocol_v3.ExtraData>();
    [global::ProtoBuf.ProtoMember(11, Name=@"extra_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<update_protocol_v3.ExtraData> extra_data
    {
      get { return _extra_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Update")]
  public partial class Update : global::ProtoBuf.IExtensible
  {
    public Update() {}
    
    private string _label = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"label", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string label
    {
      get { return _label; }
      set { _label = value; }
    }
    private int _mod_version = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mod_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mod_version
    {
      get { return _mod_version; }
      set { _mod_version = value; }
    }
    private bool _lhs_frame = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lhs_frame", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool lhs_frame
    {
      get { return _lhs_frame; }
      set { _lhs_frame = value; }
    }
    private int _time = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private readonly global::System.Collections.Generic.List<update_protocol_v3.LiveObject> _live_objects = new global::System.Collections.Generic.List<update_protocol_v3.LiveObject>();
    [global::ProtoBuf.ProtoMember(5, Name=@"live_objects", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<update_protocol_v3.LiveObject> live_objects
    {
      get { return _live_objects; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}